version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: rocket_postgres
    environment:
      POSTGRES_DB: rocket_tutorial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação Rocket
  app:
    build: .
    container_name: rocket_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/rocket_tutorial
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./templates:/app/templates
    restart: unless-stopped

  # Adminer para gerenciar o banco (opcional)
  adminer:
    image: adminer:4.8.1
    container_name: rocket_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
